site_name: ğŸ›¡ï¸ Ecossistema KBPrince
site_url: https://klaytonprincems.github.io/site/
site_author: PRINCE, K.B
site_description: SuÃ­te modular de anÃ¡lise preditiva, monitoramento de incidentes e produtividade, entreterimento, finanÃ§as.
copyright: Â© T! SOS Sistemas 2026


nav:
  - ğŸ  Home: index.md  # Este deve ser o docs/index.md com seus badges
  - InstalaÃ§Ã£o: configuracao_execucao.md
  - Jogos:
      - ğŸ€ Mega SIPP Advanced: mega_sena.md
      - âœŠ JokenpÃ´ : jokenpo.md
      - ğŸ° HanÃ³i : hanoi.md
  - Noticas:
      - Agregador: noticias.md
  - SOC:
      - Monitoramento: soc.md
  - FinanÃ§a:
      - Bovespa: bovespa.md

